### ISSUE TITLE
Check for memory leaks on redis module

### ISSUE THREAD

**Issue by aviggiano** [aviggiano/redis-roaring#13]
Since running valgrind on redis does not report memory leaks on redis modules, we can't know for sure if this module is correct.

**Comment by lemire** [comment]
Do you have reasons to suspect a memory leak?

**Comment by aviggiano** [comment]
No, but I noticed that if I purposely forget to free some allocated memory on my redis module I don't see it as a memory leak on valgrind. 

I don't think that it has anything to do with CRoaring or redis.
