### ISSUE TITLE
consider joining forces with GoodFORM?

### ISSUE THREAD

**Issue by lemire** [aviggiano/redis-roaring#56]
There is an initiative to keep Redis modules open:

https://github.com/GoodFORM

It could be interesting to investigate closer collaboration?

**Comment by aviggiano** [comment]
Closing this after having talked to GoodFORM

> I think at this early stage in
> GoodFORM's life we are going to concentrate our efforts on maintaining
> the Redis modules that were previously under the umbrella of Redis Labs
> rather than incorporating others.
> We only have a limited amount of time and bandwidth to dedicate to
> this, alas. If we change this, we will let you know.
