### ISSUE TITLE
Dockerfile Not Working

### ISSUE THREAD

**Issue by yogikannan01** [aviggiano/redis-roaring#57]
Hi Team, 

 I have just used the Dockerfile and run the below command.

docker build -t redis-roaring
docker run -p 6379:6379 redis-roaring:latest

Getting the below error while running the container.

                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.4 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 30 Apr 2019 12:10:38.559 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 30 Apr 2019 12:10:38.559 # Server initialized
1:M 30 Apr 2019 12:10:38.559 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 30 Apr 2019 12:10:38.559 # Module /usr/local/lib/libredis-roaring.so failed to load: libroaring.so: cannot open shared object file: No such file or directory
1:M 30 Apr 2019 12:10:38.559 # Can't load module from /usr/local/lib/libredis-roaring.so: server aborting

**Comment by aviggiano** [comment]
Hello @yogikannan01

Thank you for trying this module out. I will see if I can reproduce this feature and will get back to you shortly.

**Comment by yogikannan01** [comment]
Hello @aviggiano , Any update on this please.

**Comment by yogikannan01** [comment]
Hi @aviggiano , I have generated the libroaring.so shared object file from https://github.com/RoaringBitmap/CRoaring.
and same i have copied to /usr/local/lib/ and its started working.

**Comment by aviggiano** [comment]
@yogikannan01 hey
Sorry for the late reply. I will only be able to take a look at this over the weekend, but I guess your solution will work great. Probably the docker image is outdated, that's why it wasn't working.
