### ISSUE TITLE
Is there any way  to load serializable roaringbitmap into redis?

### ISSUE THREAD

**Issue by sydt2014** [aviggiano/redis-roaring#62]
I already generate some roaringbitmap saved in serializable file on disk. Is there is any way load these roaringbitmap into redis and remain roaringbitmap data type?

**Comment by aviggiano** [comment]
Hey, thank you for using this module.
Yes there is, I believe you just need to SAVE/LOAD your redis data, but I need to create a short example to show how to do it, because I don't remember exactly. I'll get back to you soon.

**Comment by aviggiano** [comment]
Hello @sydt2014, I believe you can [load the RDB](https://stackoverflow.com/questions/14497234/how-to-recover-redis-data-from-snapshotrdb-file-copied-from-another-machine) file after issuing a `SAVE` command to write your roaring bitmaps to disk. Let me know if you have any problems.
