### ISSUE TITLE
please update docker image

### ISSUE THREAD

**Issue by jiangtao244** [aviggiano/redis-roaring#70]
Remove this line
https://github.com/aviggiano/redis-roaring/blob/787744bd30d74889274ead03e3ac399a2b640852/Dockerfile#L25

**Comment by jiangtao244** [comment]
This image also should be updated.
[https://hub.docker.com/r/aviggiano/redis-roaring](url)

**Comment by aviggiano** [comment]
Thanks for the heads up. I will migrate to github actions soon and will also remember to fix this.

**Comment by aviggiano** [comment]
@jiangtao244 Done!
It's now part of the build process on github actions: https://github.com/aviggiano/redis-roaring/runs/1345311802

**Comment by jiangtao244** [comment]
Great job!
