### ISSUE TITLE
if the redis restart,Is the data still there

### ISSUE THREAD

**Issue by sunyaf** [aviggiano/redis-roaring#74]

**Comment by aviggiano** [comment]
Hello,

Yes, if you issue the `SAVE` command the data will be stored on disk and will be retrieved upon restart. 
This is tested right here: https://github.com/aviggiano/redis-roaring/blob/master/test.sh#L76

**Comment by aviggiano** [comment]
Closing this since it seems it is already resolved.
If you still have problems, feel free to open a new issue.
