### ISSUE TITLE
RedisRoaring coredump while r.optimize on non-existing key

### ISSUE THREAD

**Issue by arthurkiller** [aviggiano/redis-roaring#83]
![image](https://user-images.githubusercontent.com/11133870/124774204-34cb4500-df70-11eb-9575-4b3f328397db.png)

at line 219

if key did not exist, this should not go through with `bitmap_optimize(bitmap);`

**Comment by aviggiano** [comment]
Hi @arthurkiller 
Thank you for submitting this issue

If I understand correctly, you are getting a core dump (segfault) when using `R.OPTIMIZE` on a non-existing key?
If that's the case, that should probably be a bug. I believe there are tests that cover this case unfortunately
I'll check it out, and if this is the case, will submit a fix

**Comment by aviggiano** [comment]
Whoa, you're already submitting the bugfix! great!!! I'll get that merged once the PR is opened

**Comment by arthurkiller** [comment]
lol, I was just finish my daily work and planning to submit the code then go home.

thx for your reply. (that's a real-time reply)

**Comment by arthurkiller** [comment]
closed via #84
